Repository andela/travel_tool_back, pull requests merged in 2018-11, with the labels that each got.

#153 #160751499 Configure commitplease to check commit messages adhere to playbook's standards.
  package.json
  src/modules/occupations/OccupationsController.js
  src/modules/occupations/__tests__/occupations.test.js
  yarn.lock
Labels: ready

#152 #161646318 Update occupation seed
  src/database/seeders/20180923144040-occupations.js
Labels: ready

#148 #161509243 Restore deleted travel checklist Items
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData2.js
  src/modules/travelChecklist/__tests__/updateChecklistItem.test.js
  yarn.lock
Labels: ready

#150 reconfigure eslint and fix errors
  .eslintrc
  .eslintrc.json
  package.json
  src/database/migrations/20180828101959-create-user.js
  src/database/migrations/20180901075055-create-comment.js
  src/database/migrations/20180921005932-create-occupation.js
  src/database/seeders/20180816103706-default-role.js
  src/database/seeders/20180923144040-occupations.js
  src/database/seeders/20180927152303-users.js
  src/database/seeders/20180927152407-guesthouses.js
  src/database/seeders/20180927153917-rooms.js
  src/database/seeders/20180927154238-beds.js
  src/database/seeders/20180927154459-requests.js
  src/database/seeders/20180927156412-trip.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/requests/index.js
  src/modules/analytics/travelRequests/__tests__/travelAnalytics.test.js
  src/modules/analytics/travelRequests/analyticsController.js
  src/modules/approvals/ApprovalsController.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/includeBed.test.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/userRole/MailTravelMembers.js
  src/modules/userRole/__tests__/userRole.test.js
  yarn.lock
Labels: ready

#162 #161774275 Use yarn to install dependencies
  docker/dev/Dockerfile
Labels: devops-review

#159 #161744068 Fix guest room change issue
  src/middlewares/tripValidator.js
  src/modules/trips/__tests__/TripsController.test.js
Labels: ready

#155 #161699088 Trip planner return data
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/createTravelChecklist.test.js
  src/modules/travelChecklist/__tests__/deleteTravelCheckList.test.js
Labels: ready

#161 #161596122 Delete document
  src/modules/documents/DocumentsController.js
  src/modules/documents/__tests__/__mocks__/deleteDocumentMock.js
  src/modules/documents/__tests__/deleteDocument.test.js
  src/modules/documents/index.js
Labels: ready

#146 #161477594 Allow addition and deletion of rooms while editing guest house
  .eslintrc
  src/database/migrations/20181107113448-add-isDeleted-column.js
  src/database/models/room.js
  src/helpers/guestHouse/index.js
  src/modules/analytics/travelRequests/analyticsController.js
  src/modules/analytics/trips/__tests__/trips.test.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/editGuestHouse.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
Labels: ready

#157 #161374570 Fix travel duration and lead times analysis csv
  .gitignore
  Analytics.zip
  dashboard analytics.zip
  package.json
  src/modules/analytics/travelRequests/__mocks__/travelAnalyticsData.js
  src/modules/analytics/travelRequests/__tests__/travelAnalytics.test.js
  src/modules/analytics/travelRequests/analyticsController.js
  yarn.lock
Labels: ready

#165 #161595888 Rename travel documents
  src/middlewares/DocumentsValidator.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/modules/documents/DocumentsController.js
  src/modules/documents/__tests__/__mocks__/mockDocuments.js
  src/modules/documents/__tests__/fetchDocuments.test.js
  src/modules/documents/__tests__/updateDocument.test.js
  src/modules/documents/index.js
Labels: ready

#158 #161748761 Add New Environment Variables
  .circleci/utils.sh
  .env.example
Labels: devops-review

#105 #161044953 User can plan for an approved trip
  .env.example
  src/app.js
  src/database/seeders/20180927152303-users.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/mocks/mockData.js
  src/modules/travelChecklist/__tests__/travelChecklist.test.js
  src/modules/travelChecklist/__tests__/upload.yml
  src/modules/travelChecklist/index.js
Labels: ready

#168 #161646967 Fix yarn version inconsistency
  .circleci/config.yml
  docker/dev/Dockerfile
  docker/release/Dockerfile
  docker/tests/Dockerfile
  docker/tests/entrypoint.sh
  package.json
Labels: ready

#170 #161920682 Rename document name bug.
  src/middlewares/DocumentsValidator.js
  src/middlewares/__mocks__/index.js
  src/modules/documents/index.js
Labels: ready

#151 #161618118 Fix checklist percentage error
  src/helpers/travelChecklist/index.js
  src/modules/centers/__tests__/changeCenter.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/NotificationsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData.js
  src/modules/travelChecklist/__tests__/travelChecklistPercentage.test.js
Labels: ready

#172 #161918045 Calculate travel readiness
  src/helpers/travelChecklist/index.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/travelChecklistPercentage.test.js
Labels: ready

#175 #162039447: Fix seed data for Nairobi guesthouses in Nairobi
  src/database/seeders/20180927152407-guesthouses.js
Labels: ready

#176 #162039621 Fix file download issue on travel-readiness
  src/helpers/validators.js
  src/modules/analytics/travelReadiness/ReadinessController.js
  src/modules/analytics/travelReadiness/__tests__/readiness.test.js
Labels: ready

#179 #162046605 Modify pending requests filters
  src/modules/analytics/travelRequests/__mocks__/travelAnalyticsData.js
  src/modules/analytics/travelRequests/analyticsController.js
Labels: PEER-REVIEW

#178 #161051781 User can delete a request with 'open' status
  src/database/migrations/20181120130105-add-delete-column-request.js
  src/database/migrations/20181121034325-delete-trips.js.js
  src/database/migrations/20181122090543-add-delete-column-approval.js
  src/database/models/Approval.js
  src/database/models/request.js
  src/database/models/trip.js
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
Labels: ready

#174 #162008362 Fix checklist submission issues
  src/config/database.js
  src/database/migrations/20181008211701-create-checklist-submission.js
  src/database/seeders/20181009175951-checklistItems.js
  src/database/seeders/20181009180012-checklistItemResources.js
  src/database/seeders/20181121081032-default-checklist-item.js
  src/database/seeders/20181121081353-default-checklistItem-Resources.js
  src/helpers/travelChecklist/index.js
  src/middlewares/__mocks__/index.js
  src/middlewares/checklistValidator.js
  src/middlewares/index.js
  src/middlewares/tripValidator.js
  src/modules/analytics/travelReadiness/__tests__/readiness.test.js
  src/modules/requests/RequestsController.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData.js
  src/modules/travelChecklist/__tests__/getTravelChecklist.test.js
  src/modules/travelChecklist/__tests__/mocks/mockData.js
  src/modules/travelChecklist/__tests__/travelChecklist.test.js
  src/modules/travelChecklist/__tests__/travelChecklistPercentage.test.js
  src/modules/travelChecklist/__tests__/travelChecklistSubmission.test.js
  src/modules/travelChecklist/index.js
Labels: ready

#184 Restructure roles view to reflect current mockup
  package.json
  src/modules/centers/CentersController.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/userRole/UserRoleController.js
Labels: PEER-REVIEW

#149 #161374998 View travel calendar showing itinerary of travellers
  src/database/migrations/20181008211701-create-checklist-submission.js
  src/database/models/trip.js
  src/database/seeders/20181009180029-checklistSubmissions.js
  src/exceptions/__tests__/baseException.test.js
  src/exceptions/baseException.js
  src/exceptions/travelCalendarExceptions.js
  src/helpers/Error.js
  src/helpers/centers.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/middlewares/travelCalendarValidator.js
  src/modules/analytics/index.js
  src/modules/analytics/travelCalendar/TravelCalendar.js
  src/modules/analytics/travelCalendar/__tests__/TravelCalendar.test.js
  src/modules/analytics/travelCalendar/__tests__/__mocks__/travelCalendarData.js
  src/modules/analytics/travelCalendar/fields.js
  src/modules/analytics/travelCalendar/utils.js
  yarn.lock
Labels: ready

#186 #161925899 Change requiresFiles in travel details seeder
  src/database/seeders/20181121081032-default-checklist-item.js
Labels: ready

#181 #162113738 Make Commands Dependent
  Makefile
Labels: devops-review

#180 #162045684 Enable travel team members verify requests
  src/config/database.js
  src/database/migrations/20181120140239-update-request-status-enum.js
  src/database/migrations/20181121132608-update-approval-status-enum.js
  src/helpers/approvals/index.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/switchMessage.js
  src/helpers/requests/index.js
  src/helpers/requests/paginationHelper.js
  src/helpers/validators.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/index.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/getTravelChecklist.test.js
  src/modules/travelChecklist/__tests__/travelChecklistPercentage.test.js
  src/modules/travelChecklist/__tests__/travelChecklistSubmission.test.js
Labels: ready

#182 #161094936 Mail travel team members
  .env.example
  package.json
  src/app.js
  src/config/environment.js
  src/config/utils.js
  src/helpers/email/__tests__/switchButtonText.test.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/middlewares/tripValidator.js
  src/modules/userRole/MailTravelMembers.js
  src/modules/userRole/__tests__/mailTravelMembers.test.js
Labels: ready

#177 #162046982 Toggle travel readiness for outflow and inflow on a specific center
  src/helpers/validators.js
  src/modules/analytics/travelReadiness/ReadinessController.js
  src/modules/analytics/travelReadiness/__tests__/readiness.test.js
Labels: ready

#188 #162232273 Allow travel team members to view dashboard
  src/modules/analytics/index.js
Labels: TC/TTL Review

#187 #162192488 Use Alpine Images
  .circleci/build_deploy.sh
  .circleci/config.yml
  .circleci/gcloud_login.sh
  .circleci/images/base-image/Dockerfile
  .circleci/utils.sh
  Makefile
  docker/dev/Dockerfile
  docker/dev/docker-compose.yml
  docker/dev/entrypoint.sh
  docker/release/Dockerfile
  docker/tests/Dockerfile
  docker/tests/docker-compose.yml
  docker/tests/entrypoint.sh
Labels: devops-review

#191 Install Rok8s Scripts on Base Image
  .circleci/config.yml
  .circleci/images/base-image/Dockerfile
Labels: devops-review

#192 Update setup_k8s.sh Filename
  .circleci/config.yml
Labels: devops-review

#189 #162181636 Enforce proper checkin by users in guest house rooms
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
Labels: TC/TTL Review

#185 #162152454 Update or delete maintenance records
  src/database/migrations/20181123061939-add-delete-column-maintainance.js
  src/database/models/maintainance.js
  src/middlewares/__mocks__/index.js
  src/middlewares/guestHouseValidator.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/deleteMaintenance.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/__tests__/updateMaintenance.test.js
  src/modules/guestHouse/index.js
Labels: TC/TTL Review

#194 #162299354 Modify pending requests implementation
  src/modules/analytics/travelRequests/analyticsController.js
Labels: TC/TTL Review

#197 fix(request): no beds found on making requests
  src/modules/guestHouse/RoomsManager.js
Labels: TC/TTL Review
