Repository andela/travel_tool_back, pull requests merged in 2018-12, with the labels that each got.

#198 #162197071 Super admin can edit user role
  src/middlewares/RoleValidator.js
  src/modules/userRole/UpdateRoleController.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/__tests__/userRole.test.js
  src/modules/userRole/index.js
Labels: TC/TTL Review

#200 #162305343 Disable and restore guesthouses
  src/database/migrations/20181203102954-guesthouse-add-disabled-column.js
  src/database/models/guesthouse.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/RoomsManager.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/guestHouse/index.js
Labels: PEER-REVIEW

#203 #162378697 Fix validation for maintenance request body
  src/middlewares/Validator.js
Labels: TC/TTL Review

#205 #162006041 Fix create multi city request
  src/modules/requests/RequestsController.js
Labels: TC/TTL Review

#204 #162376440 Add checklist item validations
  src/middlewares/__mocks__/index.js
  src/middlewares/checklistValidator.js
  src/modules/travelChecklist/index.js
Labels: TC/TTL Review

#206 #162382135 Fix validation for trip room booking
  src/middlewares/tripValidator.js
  src/modules/trips/TripsController.js
Labels: TC/TTL Review

#208 #162421358 Fix manager change on request approval bug
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: TC/TTL Review

#202 #162378667 Fix the dropdown for available rooms
  src/database/models/maintainance.js
  src/modules/guestHouse/RoomsManager.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
Labels: TC/TTL Review

#201 #162375965 Validation for guest house and guesthouse-room names
  src/database/migrations/20180913094402-update-guesthousename-to-unique.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/index.js
Labels: TC/TTL Review

#209 #162407187 Create seeders for different environments
  .sequelizerc
  Makefile
  package.json
  src/database/seeders/default/20180816103706-default-role.js
  src/database/seeders/default/20180816103707-demo-user.js
  src/database/seeders/default/20180923144040-occupations.js
  src/database/seeders/default/20180927152303-users.js
  src/database/seeders/default/20180927152407-guesthouses.js
  src/database/seeders/default/20180927153917-rooms.js
  src/database/seeders/default/20180927154238-beds.js
  src/database/seeders/default/20180927154459-requests.js
  src/database/seeders/default/20180927156412-trip.js
  src/database/seeders/default/20181004161227-demo-guest-house.js
  src/database/seeders/default/20181004163514-demo-rooms.js
  src/database/seeders/default/20181004165232-demo-beds.js
  src/database/seeders/default/20181004171001-demo-guest-requests.js
  src/database/seeders/default/20181004171126-demo-trips.js
  src/database/seeders/default/20181004171127-demo-user-role.js
  src/database/seeders/default/20181009180029-checklistSubmissions.js
  src/database/seeders/default/20181010221559-default-centers.js.js
  src/database/seeders/default/20181022180012-document.js
  src/database/seeders/default/20181121081032-default-checklist-item.js
  src/database/seeders/default/20181121081353-default-checklistItem-Resources.js
  src/database/seeders/e2e/20180927152303-users.js
  src/database/seeders/unittesting/20181004171127-demo-user-role.js
Labels: TC/TTL Review

#207 #162382620 Disable user from viewing checklist items of their location
  src/helpers/centers.js
  src/helpers/travelChecklist/index.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/travelChecklistSubmission.test.js
Labels: TC/TTL Review

#211 #162573374 Fix bug with one way requests
  src/modules/requests/RequestsController.js
Labels: TC/TTL Review

#214 #162636597 Create seeders for e2e tests
  src/database/seeders/e2e/20180927152303-create-user.js
  src/database/seeders/e2e/20180927152303-users.js
  src/database/seeders/e2e/20181212181815-create-requests.js
  src/database/seeders/e2e/20181213094840-create-roles.js
  src/database/seeders/e2e/20181213122638-create-user-role.js
  src/database/seeders/e2e/20181213133608-create-occupations.js
  src/database/seeders/e2e/20181213133655-create-checklist-item.js
Labels: TC/TTL Review

#213 #162573849 Allow one way trips with a default return date
  src/helpers/validators.js
  src/modules/requests/__tests__/requests.test.js
Labels: TC/TTL Review

#217 #162375845 Update users seeder for e2e tests
  src/database/seeders/e2e/20180927152303-create-user.js
Labels: TC/TTL Review

#215 #162122460 E2E: Seed necessary data for running request edit tests
  src/database/seeders/e2e/20181213160431-edit-requests.js
Labels: TC/TTL Review

#216 #162127512 Seeders file for Approvals and Trips
  src/database/seeders/e2e/20181213073028-approval-trips.js
  src/database/seeders/e2e/20181213073028-e2e-approved-request.js
Labels: TC/TTL Review

#219 #162696526 Seed approvals and user without explicitly setting an id
  src/database/seeders/e2e/20180927152303-create-user.js
  src/database/seeders/e2e/20181213073028-e2e-approved-request.js
Labels: PEER-REVIEW

#221 #162712003 Send email to travel admins of user's origin and destination on check-in.
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchMessage.js
  src/modules/notifications/NotificationEngine.js
  src/modules/trips/TripUtils.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
Labels: PEER-REVIEW

#220 #162712399 send an email with survey link on checkout
  src/helpers/email/__tests__/switchButtonText.test.js
  src/helpers/email/checkoutTemplate.js
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/modules/notifications/NotificationEngine.js
  src/modules/trips/TripsController.js
Labels: TC/TTL Review

#224 #162711180 Fix accommodations requests for roundtrips
  src/database/migrations/20181220152025-add-accommodation-type.js
  src/database/models/trip.js
  src/modules/requests/RequestsController.js
Labels: TC/TTL Review

#227 #162789718 User can only check in if request is verified
  src/middlewares/__mocks__/index.js
  src/middlewares/tripValidator.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
  src/modules/trips/index.js
Labels: TC/TTL Review

#228 #162809348 Add New Environment Variable
  .circleci/utils.sh
Labels: devops-review

#222 #162712300 Send email notification to travel admins when the user checks-out of the guest house
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/__tests__/notificationEngine.test.js
  src/modules/trips/TripUtils.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
Labels: TC/TTL Review
