Repository andela/travel_tool_back, pull requests merged in 2018-10, with the labels that each got.

#74 #160843273 Fix view-details link on notifications for posted comments
  src/modules/comments/CommentsController.js
Labels: ready

#72 #160710722 Enable travel administrator to view accommodation centres
  src/database/migrations/20180828101958-create-user.js
  src/database/migrations/20180913094401-create-guest-house.js
  src/database/migrations/20180913094410-create-rooms.js
  src/database/migrations/20180913094420-create-bed.js
  src/database/migrations/20180913094426-create-trip.js
  src/database/models/bed.js
  src/database/models/guesthouse.js
  src/database/models/room.js
  src/database/models/trip.js
  src/database/models/user.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/index.js
  src/modules/index.js
Labels: ready

#65 #160710694 Create Guest House Api
  src/database/migrations/20180828101958-create-user.js
  src/database/migrations/20180828101959-create-user.js
  src/database/models/trip.js
  src/database/models/user.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/index.js
Labels: ready

#76 #160710842 Edit guest house centre
  src/database/migrations/20180927102259-add-booked.js
  src/database/models/bed.js
  src/helpers/guestHouse/index.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/editGuestHouse.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/index.js
Labels: ready

#80 #160715616 Check in to guesthouse
  src/database/migrations/20180928135008-update-trip.js
  src/database/models/rooms.js
  src/database/models/trip.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/middlewares/tripValidator.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/index.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
  src/modules/trips/index.js
  src/modules/userRole/__tests__/userRole.test.js
Labels: ready

#81 #160715637 Checkout of Guest Houses
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/index.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
Labels: ready

#78 #160710724 Enable Travel Administrator to View Further Guest House Details
  .eslintrc
  src/database/migrations/20180828101958-create-user.js
  src/helpers/guestHouse/index.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/getGuestHouseDetails.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/index.js
Labels: ready

#86 #160820749 Email notification on approval
  src/config/database.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchMessage.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/__tests__/notificationEngine.test.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/userRole/UserRoleController.js
Labels: ready

#82 #160815252 Mark single notification as read
  src/middlewares/authenticate.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/notifications/index.js
Labels: ready

#85 #160820759 Send Email Notification for Posted Comment
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/switchMessage.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#70 #160710730 Mark room as faulty
  src/database/migrations/20180913094410-create-room.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/guestHouse/__tests__/mocks/guestHouseData.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/guestHouse/index.js
  src/modules/index.js
Labels: ready

#84 #160820728 Email notification for edited travel requests
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/switchMessage.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/trips/TripsController.js
Labels: ready

#35 #160157497 Setup bugsnag for error reporting
  .circleci/config.yml
  .circleci/utils.sh
  .env.example
  package.json
  src/app.js
  src/config/environment.js
  src/config/utils.js
  yarn.lock
Labels: devops-review

#95 #160710730 Tests for marking room as faulty
  .env.example
  src/modules/guestHouse/__tests__/updateRoomStatus.test.js
  yarn.lock
Labels: ready

#113 #161158698 Fix Sequelize error when trying to create guesthouse
  src/database/seeders/20181004165232-demo-beds.js
  src/database/seeders/20181004171126-demo-trips.js
Labels: PEER-REVIEW

#68 160525336 Get post occupations
  package.json
  src/database/migrations/20180921005932-create-occupation.js
  src/database/models/occupation.js
  src/database/seeders/20180923144040-occupations.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/index.js
  src/modules/occupations/OccupationsController.js
  src/modules/occupations/__tests__/mocks/mockData.js
  src/modules/occupations/__tests__/occupations.test.js
  src/modules/occupations/index.js
  yarn.lock
Labels: ready

#123 #160710678 Create travel team members on travela
  package.json
  src/app.js
  src/database/migrations/20181010072325-create-center.js
  src/database/migrations/20181010082325-create-user-role.js
  src/database/migrations/20181010104815-remove-role-id-column.js
  src/database/models/Center.js
  src/database/models/UserRole.js
  src/database/models/role.js
  src/database/models/user.js
  src/database/seeders/20180816103707-demo-user.js
  src/database/seeders/20180927152303-users.js
  src/database/seeders/20181004171127-demo-user-role.js
  src/database/seeders/20181010221559-default-centers.js.js
  src/middlewares/RoleValidator.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/modules/centers/CentersController.js
  src/modules/centers/__tests__/CentersController.test.js
  src/modules/centers/__tests__/mocks/mockData.js
  src/modules/centers/index.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/editGuestHouse.test.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/guestHouse/__tests__/getGuestHouseDetails.test.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/guestHouse/__tests__/updateRoomStatus.test.js
  src/modules/guestHouse/index.js
  src/modules/index.js
  src/modules/requests/__tests__/includeBed.test.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/userRole/UserRoleController.js
  src/modules/userRole/__tests__/travelTeamRole.test.js
  src/modules/userRole/__tests__/userRole.test.js
  src/modules/userRole/index.js
  yarn.lock
Labels: ready

#120 #60717378 Edit travel team member center
  .eslintrc
  package.json
  src/app.js
  src/middlewares/RoleValidator.js
  src/middlewares/__mocks__/index.js
  src/modules/centers/CentersController.js
  src/modules/centers/__tests__/changeCenter.test.js
  src/modules/centers/index.js
  src/modules/userRole/UserRoleController.js
  yarn.lock
Labels: ready

#97 #161045193 Change requester room
  src/config/database.js
  src/database/migrations/20180919124130-create-changed-room.js
  src/database/models/ChangedRoom.js
  src/database/models/bed.js
  src/database/models/request.js
  src/database/models/trip.js
  src/database/models/user.js
  src/helpers/email/switchMessage.js
  src/middlewares/__mocks__/index.js
  src/middlewares/tripValidator.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
  src/modules/trips/index.js
Labels: ready

#118 161096201 Send travel survey email notification upon checkout
  src/helpers/email/__tests__/switchButtonText.test.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
Labels: ready

#119 #161050094 Reply Comment from Email
  .env.example
  package.json
  src/database/migrations/20181010142242-add-user-picture.js
  src/database/models/user.js
  src/helpers/email/__tests__/switchButtonText.test.js
  src/helpers/email/__tests__/switchMessage.test.js
  src/helpers/email/mailTemplate.js
  src/helpers/email/switchButtonText.js
  src/helpers/email/switchMessage.js
  src/middlewares/Validator.js
  src/modules/approvals/ApprovalsController.js
  src/modules/centers/__tests__/changeCenter.test.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/editGuestHouse.test.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/guestHouse/__tests__/getGuestHouseDetails.test.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/guestHouse/__tests__/updateRoomStatus.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/__mocks__/notificationsData.js
  src/modules/notifications/__tests__/notificationEngine.test.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/notifications/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/userRole/UserRoleController.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/__tests__/travelTeamRole.test.js
  src/modules/userRole/__tests__/userRole.test.js
  yarn.lock
Labels: ready

#132 #161337585 Add Environment Variable
  .circleci/utils.sh
Labels: devops-review

#133 #161044635 Fix in-app notifications arrangement
  .gitignore
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#128 Trip planning initiative
  .env.example
  package.json
  src/database/migrations/20180828101958-create-user.js
  src/database/migrations/20181008205626-create-checklist-item.js
  src/database/migrations/20181008211505-create-checklist-item-resource.js
  src/database/migrations/20181008211701-create-checklist-submission.js
  src/database/models/ChecklistItemResource.js
  src/database/models/ChecklistItems.js
  src/database/models/ChecklistSubmission.js
  src/database/models/user.js
  src/database/seeders/20180816103707-demo-user.js
  src/database/seeders/20180927152303-users.js
  src/helpers/travelChecklist/index.js
  src/helpers/validators.js
  src/middlewares/RoleValidator.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/approvals/ApprovalsController.js
  src/modules/centers/__tests__/changeCenter.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/__tests__/editGuestHouse.test.js
  src/modules/guestHouse/__tests__/getGethouses.test.js
  src/modules/guestHouse/__tests__/getGuestHouseDetails.test.js
  src/modules/guestHouse/__tests__/updateGuestHouse.test.js
  src/modules/guestHouse/__tests__/updateRoomStatus.test.js
  src/modules/index.js
  src/modules/notifications/__tests__/__mocks__/notificationsData.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/occupations/__tests__/mocks/mockData.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/travelChecklist/CloudinaryDeletion.js
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData2.js
  src/modules/travelChecklist/__tests__/createTravelChecklist.test.js
  src/modules/travelChecklist/__tests__/deleteTravelCheckList.test.js
  src/modules/travelChecklist/__tests__/getTravelChecklist.test.js
  src/modules/travelChecklist/__tests__/travelChecklistPercentage.test.js
  src/modules/travelChecklist/__tests__/updateChecklistItem.test.js
  src/modules/travelChecklist/index.js
  src/modules/trips/TripsController.js
  src/modules/trips/__tests__/TripsController.test.js
  src/modules/trips/__tests__/mocks/tripData.js
  src/modules/userRole/UserRoleController.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/__tests__/travelTeamRole.test.js
  yarn.lock
Labels: ready

#130 #160820759 Fix Email Notification for Comment
  src/modules/comments/CommentsController.js
Labels: ready

#92 #160597069 Add guest room and bed during request creation
  package.json
  src/database/models/trip.js
  src/helpers/requests/index.js
  src/helpers/validators.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/approvals/ApprovalsController.js
  src/modules/centers/__tests__/changeCenter.test.js
  src/modules/guestHouse/GuestHouseController.js
  src/modules/guestHouse/RoomsManager.js
  src/modules/guestHouse/__tests__/GuestHouseController.test.js
  src/modules/guestHouse/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/includeBed.test.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#137 #161050888 View deleted travel checklist items
  src/modules/travelChecklist/TravelChecklistController.js
  src/modules/travelChecklist/__tests__/getDeletedTravelChecklistItems.test.js
  src/modules/travelChecklist/index.js
Labels: ready

#139 #161345105 Delete travel team member
  src/middlewares/RoleValidator.js
  src/modules/travelChecklist/__tests__/__mocks__/mockData.js
  src/modules/travelChecklist/__tests__/getTravelChecklist.test.js
  src/modules/userRole/UserRoleController.js
  src/modules/userRole/__tests__/deleteUserRole.test.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/index.js
Labels: ready

#140 #161340859 Fix user can edit other user's profile
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/__tests__/userRole.test.js
  src/modules/userRole/index.js
Labels: ready

#138 #161376806 Add approver data to an approved request
  src/database/seeders/20181004161227-demo-guest-house.js
  src/middlewares/Validator.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/travelChecklist/TravelChecklistController.js
Labels: PEER-REVIEW

#145 #161340967 Add new Andela centers
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/centers/CentersController.js
  src/modules/centers/__tests__/createCenter.test.js
  src/modules/centers/index.js
Labels: ready

#143 #161450380 View trips per month analysis
  package.json
  src/helpers/Utils.js
  src/middlewares/__mocks__/index.js
  src/middlewares/analyticsValidator.js
  src/middlewares/index.js
  src/middlewares/tripValidator.js
  src/modules/analytics/index.js
  src/modules/analytics/trips/TripsController.js
  src/modules/analytics/trips/__mocks__/tripsData.js
  src/modules/analytics/trips/__tests__/trips.test.js
  src/modules/index.js
  src/modules/trips/__tests__/TripsController.test.js
  yarn.lock
Labels: ready

#136 #161094864 Email origin travel team if travel readiness 100%
  src/config/utils.js
  src/modules/requests/RequestsController.js
  src/modules/userRole/MailTravelMembers.js
  yarn.lock
Labels: ready
