Repository andela/travel_tool_back, pull requests merged in 2018-08, with the labels that each got.

#14 #159725850 Create api to add a new request to the db
  .codeclimate.yml
  .env.example
  package.json
  src/index.js
  src/middlewares/Validator.js
  src/middlewares/authenticate.js
  src/middlewares/checkValidations.js
  src/middlewares/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
  yarn.lock
Labels: completed

#25 #160165626 Add options to decode the token for staging and production environments
  src/middlewares/authenticate.js
Labels: ready

#24 #160096049 Fix incorrect open requests badge count
  .gitignore
  src/helpers/Pagination.js
  src/helpers/Utils.js
  src/middlewares/Validator.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: PEER-REVIEW
