Repository andela/travel_tool_back, pull requests merged in 2018-09, with the labels that each got.

#31 #160233501 Assigning manager role to user
  .DS_Store
  src/.DS_Store
  src/modules/requests/RequestsController.js
  src/modules/userRole/UserRoleController.js
Labels: ready

#32 #160195740 Create Endpoint To Get User Request Details
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
Labels: completed

#29 #160195763 Api endpoints to create a comment and get comments
  src/database/migrations/20180901075055-create-comment.js
  src/database/models/comment.js
  src/database/models/request.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/comments/index.js
  src/modules/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#27 #160047860 Create Approvals Model and Endpoint
  .eslintrc
  package.json
  src/app.js
  src/database/migrations/20180830053535-create-approvals-table.js
  src/database/migrations/20180830150224-add-status-column.js
  src/database/models/Approval.js
  src/database/seeders/20180830064847-seed-approvals.js
  src/helpers/Utils.js
  src/helpers/__tests__/serverError.test.js
  src/helpers/requests/index.js
  src/helpers/serverError.js
  src/index.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/modules/approvals/__mocks__/approvals.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/approvals/__tests__/mocks/mockModules.js
  src/modules/approvals/approvals.js
  src/modules/approvals/index.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/index.js
  src/modules/healthCheck/__test__/healthCheck.test.js
  src/modules/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
  src/modules/userRole/__tests__/userRole.test.js
  src/modules/userRole/index.js
Labels: ready

#36 #160195763 Fix issue with comments not getting fetched
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#34 #160196856 Make request available for approval
  src/database/migrations/20180813150917-create-request.js
  src/database/migrations/20180830053535-create-approvals-table.js
  src/database/models/Approval.js
  src/helpers/requests/index.js
  src/modules/approvals/approvals.js
  src/modules/comments/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__mocks__/approvals.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#30 #160196032 Approve and Reject request(By Requester's Manager)
  src/database/migrations/20180830053535-create-approvals-table.js
  src/database/models/Approval.js
  src/helpers/Utils.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/middlewares/index.js
  src/middlewares/validateDirectReport.js
  src/modules/approvals/__mocks__/approvals.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/approvals/__tests__/mocks/mockModules.js
  src/modules/approvals/approvals.js
  src/modules/approvals/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__mocks__/approvals.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
  src/modules/userRole/__tests__/userRole.test.js
Labels: ready

#45 #160429451 Require environment variables
  .circleci/build_deploy.sh
  .circleci/config.yml
  .circleci/utils.sh
Labels: devops-review

#42 #160381997 Send Notification to Slack When a Job Fails
  .circleci/build_deploy.sh
  .circleci/config.yml
Labels: devops-review

#49 #160448152 Export Environment Variables
  .circleci/utils.sh
Labels: devops-review

#41 #160128175 Create user profile endpoint.
  package.json
  src/database/migrations/20180828101958-create-user.js
  src/database/models/user.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/userRole/UserRoleController.js
  src/modules/userRole/__tests__/mocks/mockData.js
  src/modules/userRole/__tests__/userRole.test.js
  src/modules/userRole/index.js
Labels: ready

#39 #160196032 Approve/Reject Request (By Requester's Manager)
  src/helpers/notFoundError.js
  src/middlewares/validateDirectReport.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/__mocks__/approvals.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/approvals/__tests__/mocks/mockModules.js
  src/modules/approvals/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#48 #160370625 Implement edit comment functionality
  src/database/migrations/20180901075055-create-comment.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/index.js
Labels: ready

#46 #160371133 Server side socket setup
  package.json
  src/database/migrations/20180911084400-create-notification.js
  src/database/models/Notification.js
  src/index.js
  src/modules/comments/CommentsController.js
  src/modules/index.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/index.js
  src/modules/requests/RequestsController.js
  src/modules/userRole/UserRoleController.js
  yarn.lock
Labels: ready

#53 #160595712 Add isEdit field to the comments table
  src/database/migrations/20180901075055-create-comment.js
  src/database/models/comment.js
  src/modules/comments/CommentsController.js
Labels: ready

#52 #160370654 Enable Managers to See Full Details of Multi-city Requests
  src/database/migrations/20180813150917-create-request.js
  src/database/migrations/20180828101940-create-role.js
  src/database/migrations/20180828101958-create-user.js
  src/database/migrations/20180830053535-create-approvals-table.js
  src/database/migrations/20180913094426-create-trip.js
  src/database/models/Approval.js
  src/database/models/Trip.js
  src/database/models/request.js
  src/database/seeders/20180816103703-default-request.js
  src/database/seeders/20180914133904-seed-trips.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/userRole/__tests__/userRole.test.js
Labels: ready

#47 #160371227 Send notification for approved request
  .eslintrc
  package.json
  src/database/migrations/20180911084400-create-notification.js
  src/index.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/notifications/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#44 #160370645 Create and edit requests with status 'open'
  .codeclimate.yml
  package.json
  src/database/migrations/20180813150917-create-request.js
  src/database/migrations/20180830053535-create-approvals-table.js
  src/database/migrations/20180830150224-add-status-column.js
  src/database/migrations/20180913094426-create-trip.js
  src/database/models/Approval.js
  src/database/models/index.js
  src/database/models/request.js
  src/database/models/trip.js
  src/database/seeders/20180816103703-default-request.js
  src/database/seeders/20180830064847-seed-approvals.js
  src/database/seeders/20180914133904-seed-trips.js
  src/helpers/Error.js
  src/helpers/__tests__/Error.test.js
  src/helpers/notFoundError.js
  src/helpers/serverError.js
  src/helpers/validators.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/middlewares/validateDirectReport.js
  src/modules/approvals/ApprovalsController.js
  src/modules/approvals/__tests__/approvals.test.js
  src/modules/approvals/index.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/notifications/index.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/requests/index.js
  yarn.lock
Labels: ready

#40 #160371193 Edit Travel Request Notifications
  src/database/migrations/20180919124129-create-notification.js
  src/database/models/trip.js
  src/helpers/notFoundError.js
  src/helpers/serverError.js
  src/modules/comments/CommentsController.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#59 #160386275 Fix travel duration
  src/modules/approvals/ApprovalsController.js
  src/modules/requests/RequestsController.js
Labels: PEER-REVIEW

#54 #160371487 Mark all notifications as read
  src/helpers/notFoundError.js
  src/helpers/serverError.js
  src/middlewares/Validator.js
  src/middlewares/__mocks__/index.js
  src/modules/notifications/NotificationsController.js
  src/modules/notifications/__tests__/__mocks__/notificationsData.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/notifications/index.js
  src/modules/requests/RequestsController.js
Labels: ready

#56 #160370638 Implement delete comment functionality
  src/database/migrations/20180901075055-create-comment.js
  src/database/models/comment.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/index.js
Labels: ready

#62 #160371133 Send notification after creating a request
  src/modules/requests/RequestsController.js
Labels: ready

#58 #160371362 Requester Comments Notification
  src/modules/approvals/ApprovalsController.js
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/__tests__/notificationEngine.test.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/userRole/__tests__/userRole.test.js
  yarn.lock
Labels: ready

#55 #160370764 Search functionality endpoints
  src/helpers/Pagination.js
  src/helpers/approvals/index.js
  src/helpers/requests/index.js
  src/modules/approvals/ApprovalsController.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#63 #160783718 Update docker image when a make command is run
  Makefile
  docker/dev/Dockerfile
  docker/dev/docker-compose.yml
  docker/dev/entrypoint.sh
  docker/release/Dockerfile
  docker/tests/Dockerfile
  docker/tests/docker-compose.yml
  docker/tests/entrypoint.sh
Labels: devops-review

#67 #160371362 Send Comments Notification
  package.json
  src/modules/comments/CommentsController.js
  src/modules/comments/__tests__/comments.test.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/healthCheck/__test__/healthCheck.test.js
  src/modules/notifications/NotificationEngine.js
  src/modules/notifications/__tests__/notificationEngine.test.js
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/requests.test.js
Labels: ready

#66 #160751452 Re-order arrangement of notifications
  src/modules/notifications/NotificationsController.js
Labels: ready

#69 #160801033 Add Picture Column to Request Table
  src/database/migrations/20180927102157-add-picture.js
  src/database/models/request.js
  src/modules/comments/__tests__/mocks/mocksData.js
  src/modules/requests/RequestsController.js
  src/modules/requests/__tests__/mocks/mockData.js
Labels: ready

#71 160817425 Make All Test Independent
  src/modules/notifications/__tests__/notifications.test.js
  src/modules/requests/__tests__/requests.test.js
  src/modules/userRole/__tests__/userRole.test.js
Labels: ready
